spring:
  datasource:
    url: "jdbc:h2:mem:aries_transaction_test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;INIT=CREATE DOMAIN IF NOT EXISTS JSONB AS JSON"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  test:
    database:
      replace: none

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  secret: dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciB0ZXN0cw==
  expiration: 86400
