package com.actilazion.aries_transaction.audit.domain;

public enum AuditEventType {
    TRANSFER_INITIATED,
    TRANSFER_COMPLETED,
    TRANSFER_FAILED,
    TRANSFER_REVERSED,
    TRANSFER_REFUNDED,
    ACCOUNT_CREATED,
    ACCOUNT_FROZEN,
    ACCOUNT_CLOSED,
    TRANSFER_PREVIEW_CREATED,
    TRANSFER_PREVIEW_EXPIRED
}
